= Jenkins Javadocs

This repository contains the scripts necessary to generate javadocs for
publication to the jenkins.io infrastructure.

The link:http://javadoc.jenkins.io/[jenkins.io production site] includes:

* link:http://javadoc.jenkins.io/[Root Javadoc] for Jenkins Weekly release
* link:http://javadoc.jenkins.io//plugin[Plugin Javadoc] for many Jenkins plugins
* link:http://javadoc.jenkins.io/component[Component Javadoc] for Jenkins components and libraries (currently a partial list of components)
* link:http://javadoc.jenkins.io/archive[Archive Javadoc] for past Jenkins releases

## Development

The repository offers a `Dockerfile`,
which can be used for running the build and verifying results.

### Building image

Build command:

```shell
docker build -t jenkinsinfra/javadoc-dev --build-arg LTS_RELEASES="2.332 2.346" --build-arg PLUGINS="credentials git git-client" .
```

Optional arguments:

* `LTS_RELEASES` - list of LTS releases to be published
** Example: "2.332 2.346"
** Default: all LTS lines returned by link:https://repo.jenkins-ci.org[Jenkins Artifactory]
** Javadoc for the latest weekly will be published anyway
* `PLUGINS` - list of plugins to be published
** Example: "credentials git git-client"
** Default: all plugins by the default Jenkins update site

### Running image

Run command:

```shell
docker run --rm -p 9090:80 jenkinsinfra/javadoc-dev
```

After starting the image the update site will be available at `DOCKER_HOST:9090`,
so you will be able to browse the contents similarly to link:http://javadoc.jenkins.io/[Jenkins Javadoc].
