= Jenkins Javadocs

This repository contains the scripts necessary to generate javadocs for
publication to the jenkins.io infrastructure.

The link:http://javadoc.jenkins.io/[production site] includes:

* link:http://javadoc.jenkins.io/[index.html] - Javadoc of the Jenkins Weekly release
* link:http://javadoc.jenkins.io/archive[/archive/] - Javadoc for many releases
* link:http://javadoc.jenkins.io//plugin[/plugin/] - Javadoc for plugins
* link:http://javadoc.jenkins.io/module[/module/] - Javadoc for Jenkins Core modules
** The site lists latest versions of modules.
Effective versions in the latest core release may differ.
* link:http://javadoc.jenkins.io/component[/component/] - Javadoc for Jenkins components and libraries
** This section does not yet contain a full list of components

## Development

The repository offers a `Dockerfile`,
which can be used for running the build and verifying results.

### Building image

Build command:

```shell
docker build -t jenkinsinfra/javadoc-dev --build-arg LTS_RELEASES=2.60 --build-arg PLUGINS="git git-client github" .
```

Optional arguments:

* `LTS_RELEASES` - list of LTS releases to be published
** Example: "2.46 2.60"
** Default: all LTS lines returned by link:https://repo.jenkins-ci.org[Jenkins Artifactory]
** Javadoc for the latest weekly will be published anyway
* `PLUGINS` - list of plugins to be published
** Example: "git github git-client"
** Default: all plugins by the default Jenkins update site

### Running image

Run command:

```shell
docker run --rm -p 8080:80 jenkinsinfra/javadoc-dev
```

After starting the image the update site will be available at `DOCKER_HOST:8080`,
so you will be able to browse the contents similarly to link:http://javadoc.jenkins.io/[Jenkins Javadoc].
